# Generated by Django 5.2.9 on 2026-01-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sellorder_customer_email_sellorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
