# Generated by Django 5.2.9 on 2026-01-05 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_sellorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
