# Generated by Django 5.2.9 on 2026-01-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_sellorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
