# Generated by Django 5.2.9 on 2025-12-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop')], max_length=10)),
                ('base_price', models.IntegerField()),
            ],
        ),
    ]
